containers:
  - name: tidal-test-yaml
    image: docker.tidal.com/tidal-test-yaml:1.0.0
    ports:
      - hostPort: 9000
        containerPort: 9000
        protocol: tcp
    env:
      - name: 'ENV'
        value: test
network: host
control:
    package: tidal-fuck-yaml
    version: 1.0.0
    section: misc
    priority: optional
    architecture: all
    maintainer: Name McNamerson
    description: Blah blah blah blah
    distribution: development
