language: go
sudo: required
go:
    - 1.7.4
before_install:
    - go get github.com/mattn/goveralls
    - go get -d -v ./...
script:
    - $HOME/gopath/bin/goveralls -service=travis-ci
before_deploy:
    - make
deploy:
    skip_cleanup: true
    provider: releases
    api_key:
            secure: aBu0TeTxdAombKC0gB6ODwwr8XdJ9TCYEzoLLZLQcIxQL5JojZIFItFQBwMb//8WLaI04fRsADIoU8CF8GjPmTy1zog91iDspktnXTFdr3ADQucU5QHANmprOUX1noEGNryMZl8HWTMgiysm/iB4GgEC6y477hm8t3P3Lv4iRWjYN9rxMvqDrFOiOkALsHfhfacJsGpNVqFGv4ON3cyUjI8mMmUoww4Vyz+JzxAs+RrLYjZTvynrCgx6XGgkSNBwKA+VMkIYioFpSfbXlTJ1SxKdPGnc0S5Q0y84dnBG/epD9Rm4f1Ki+DXQ0zTvvs6Fw1slXcELvB/bEqzTuRkEPuPhMN5lA9tV7T31rAklFc1FgGWNsU7lytrhwAzUthMPJ4g+qekALQhiWsHFQm9pXQ6q6uuRleyGocAnDezkPgaKopRUlDONiRrYsDJbQ/o1has55DH8hNr32PG8WnRLiu12EtM1uBhXjgKL9sNTfSTOr3DHW4SVsapfuJq16S8Y8QcdN5Hw+7x4CiD2qA22661oXJs/us07jJJ04KfHN4RWEPTlkdmndXAegt1pzRGNgrdaf4e0ovgD31CuM8yLqaY/nqKgdj9lyt9mnTgOgw9D6qz0jhJGj1mIJsPUncqGS6KVfwqxpUZo5xQHGsKdcS5BWHaRUzIVb2QojOE4axk=
    file:
        - release/docker-service-linux-amd64
        - release/docker-service-linux-386
        - release/docker-service-linux-arm
    on:
        repo: danmademe/docker-service
        tags: true
        branch: master
